This will add the `jsxAttributesIndent` option.
arijs/prettier-with-tabs pull request #17
Opened 2017-06-10 17:42 UTC by ivank

Indenting attributes with a single space provides much more readable code, as the boundaries between attributes, child nodes and closing tags are apparent, and it scales well for large amount of tags:

```html
<div
 attr1="my attr"
 attr2="my other attr">
    <child />
    <child
     nestedAttr2="test"
     nestedAttr3="test" />
</div>
```

The name of the option is not the best though, we can certainly update that.

I got redirected to this project since the idea was not taken all that
heartly in the prettier proper. You can take a look at the discussion
there: https://github.com/prettier/prettier/pull/2082

2017-06-10 18:01 UTC, ivank commented
Weird the tests on travis are failing, but locally I get all green, it seems travis does not have enough resources to run all the tests maybe?

2017-06-11 16:28 UTC, rhengles commented
@ivank Thank you, this is awesome! I'm absolutely in favor of merging this, but first I have a concern. What happens to multiline attributes in JSX, for example, objects, arrays or functions? Does this only add a space to the first line, or to all of them?

Also, I think the name `addition()` is not very descriptive. I would reuse the `align()` function in this way:

```diff
// src/printer.js

       return group(
         concat([
           "<",
           path.call(print, "name"),
           concat([
-            indent(
-              concat(
-                path.map(attr => concat([line, print(attr)]), "attributes")
-              )
-            ),
+            options.jsxAttributesIndent
+              ? align({ forceSpaces: 1 }, attributes)
+              : indent(attributes),
             n.selfClosing ? line : options.jsxBracketSameLine ? ">" : softline
           ]),
           n.selfClosing ? "/>" : options.jsxBracketSameLine ? "" : ">"
        ])
      );
```

```diff
// src/doc-printer.js

function makeAlign(ind, n) {
    if (n === -Infinity) {
      return {
       indent: 0,
       align: {
         spaces: 0,
         tabs: 0
       }
     };
   }

+  if (!isNaN(n.forceSpaces)) {
+    return {
+      indent: ind.indent,
+      align: {
+        spaces: ind.align.spaces,
+        tabs: ind.align.tabs,
+        forceSpaces: n.forceSpaces
+      }
+    };
+  }
 
   return {
     indent: ind.indent,
     align: {
       spaces: ind.align.spaces + n,
       tabs: ind.align.tabs + (n ? 1 : 0)
     }
   };
 }

// { ... }

                 const length = ind.indent * options.tabWidth + ind.align.spaces;
                 const indentString = options.useTabs
                   ? "\t".repeat(ind.indent + ind.align.tabs)
                   : " ".repeat(length);
-                out.push(newLine + indentString);
+
+                if (ind.align.forceSpaces) {
+                  indentString += " ".repeat(ind.align.forceSpaces);
+                }
+
+                out.push(newLine + indentString);
                 pos = length;
```

2017-06-12 07:22 UTC, ivank commented
Great idea! I was struggling with appropriate name :) Will do that today, and check if it work with objects as well.

2017-06-12 11:55 UTC, ivank commented
@rhengles update with your suggestion, and modified so it works better with multiline objects inside attributes. Hope you like it.

2017-06-21 13:34 UTC, rhengles requested changes
I am sorry I've taken so long to respond this, I was very busy last week.

Please, I asked some changes to make this sollution a little more generic and future-proof.

This also needs to be documented on the `README.md`, the official documentation.

If you can make these changes, I'm planning to release a new version with the last fixes and PRs merged.

Thank you!

2017-06-21 13:34 UTC, rhengles commented on src/doc-printer.js
> +  if (isNaN(n) && n.forceSpace) {
Please, I would really prefer that this was a Number: `&& !isNaN(n.forceSpaces)`

2017-06-21 13:34 UTC, rhengles commented on src/printer.js
> +              ? align({ forceSpace: true }, attributes)
and this `align({ forceSpaces: 1 }, attributes)`

2017-06-21 13:34 UTC, rhengles commented on src/options.js
> +  jsxAttributesIndent: false,
Also, I think `jsxAttributesAlignTagName` or `jsxAttrAlignTagName` may be a better name

2017-06-21 13:34 UTC, rhengles commented on src/doc-printer.js
> +        forceSpace: ind.indent
And this `forceSpaces: n.forceSpaces`

2017-06-21 13:34 UTC, rhengles commented on src/doc-printer.js
> +                }
And this:

```javascript
if (ind.align.forceSpaces) {
  indentString += " ".repeat(ind.align.forceSpaces);
}
```

2017-06-21 13:44 UTC, rhengles commented
> BTW @rhengles your docs/index.js looks to be rather badly out of sync. I've had to not stage quite a lot of changes that were obviously not from my code. Maybe I'm missing some flag when generating it?

No, you're right - the entire docs folder *is* out of sync and needs to be updated, but please don't bother with that on this PR.

2017-11-02 13:23 UTC, ivank commented
I'm closing this as I've implemented this as a [up-to-date fork of the main prettier repo](https://github.com/enhancv/prettier)

2017-11-02 13:23 UTC, closed without merging